spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8888  # ‚Üê IMPORTANTE
  cloud:
    config:
      enabled: true
      fail-fast: false
  datasource:
    url: jdbc:postgresql://localhost:5435/notificationdb
    username: notificationuser
    password: notificationpass
  kafka:
    bootstrap-servers: localhost:9094

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/