spring:
  application:
    name: trip-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
      fail-fast: false
  datasource:
    url: jdbc:postgresql://localhost:5432/tripdb
    username: tripuser
    password: trippass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9094

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/